### ISSUE TITLE
I want a go at this project reviving / sponsoring

### ISSUE THREAD

**Issue by gjvanderheiden** [lvgl/lv_binding_cpp#11]
[https://github.com/gjvanderheiden/lv_binding_cpp](https://github.com/gjvanderheiden/lv_binding_cpp)

Put many weeks in this and used the python bindings as a very raw staring point.

It used it to generate v8 en v9 code. It uses Jinja2 templates ( https://github.com/gjvanderheiden/lv_binding_cpp/tree/master/gen).

I think I met all the criteria in the current README.md

**Comment by kisvegabor** [comment]
Amazing! Let's continue in #10.
